#docker-compose.yml
version: "3.4"
services:
  web:
    image: drdgz/flaskapp-15:latest
    ports:
      - "5000:5000"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - webnet
networks:
  webnet:
